version: '3.8'
name: rinha-backend-local

services:
  postgres:
    image: postgres:latest
    command: postgres -c 'max_connections=600'
    user: postgres
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 3s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"