name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: docker build . -t fzanutto/rinha-backend
  test:
    runs-on: ubuntu-20.04
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker-compose up

      