name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'gradle'
      - name: Build
        run: docker build . -t fzanutto/rinha-backend
  test:
    runs-on: ubuntu-20.04
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'gradle'
      - run: |
          docker-compose up

